[2024-12-22T16:05:44.154+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-22T16:05:44.180+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.load_data_to_postgres manual__2024-12-22T14:55:10.356955+00:00 [queued]>
[2024-12-22T16:05:44.191+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.load_data_to_postgres manual__2024-12-22T14:55:10.356955+00:00 [queued]>
[2024-12-22T16:05:44.193+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 5
[2024-12-22T16:05:44.209+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data_to_postgres> on 2024-12-22 14:55:10.356955+00:00
[2024-12-22T16:05:44.220+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=901) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-22T16:05:44.226+0000] {standard_task_runner.py:72} INFO - Started process 903 to run task
[2024-12-22T16:05:44.225+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_top_best_sellers_books', 'load_data_to_postgres', 'manual__2024-12-22T14:55:10.356955+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpu6z2nwk5']
[2024-12-22T16:05:44.230+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask load_data_to_postgres
[2024-12-22T16:05:44.680+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_top_best_sellers_books.load_data_to_postgres manual__2024-12-22T14:55:10.356955+00:00 [running]> on host c50092bbd7fa
[2024-12-22T16:05:44.806+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_top_best_sellers_books' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T14:55:10.356955+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-22T14:55:10.356955+00:00'
[2024-12-22T16:05:44.815+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-22T16:05:44.962+0000] {dag_test.py:51} ERROR - {'author_dim':                       Author  author_id
0                 Paperback,          1
1           Martin Kleppmann          2
2                Alex Petrov          3
3    Cole Nussbaumer Knaflic          4
4             Charity Majors          5
5                Jay Wengrow          6
6                    Kindle,          7
7           Catherine Nelson          8
8             James Densmore          9
9              Scott E. Page         10
10             Bill Chambers         11
11         Steven L. Brunton         12
12                Hardcover,         13
13          Robert S. Seiner         14
14               Kevin Kelly         15
15              James Gleick         16
16             Kevin Mitnick         17
17            Wilpen L. Gorr         18
18               Bill Karwin         19
19             Kenneth Field         20
20           Allen B. Downey         21
21                    Kindle         22
22             Stefan Jansen         23
23          Michael P. Lynch         24
24        Bradford Tuckfield         25
25        Audible Audiobook,         26
26                 Paperback         27
27                eTextbook,         28
28            Tamer Khraisha         29
29             Alan Beaulieu         30
30          John Ladley B.A.         31
31              Jeff Prosise         32
32              Hannes Hapke         33
33        Ole Olesen-Bagneux         34
34             Pulkit Chadha         35
35             Andy Petrella         36
36              Dan Sullivan         37
37             Paul Crickard         38
38       Piethein Strengholt         39
39      Mehdi Nourbakhsh PhD         40
40             Chris Okasaki         41
41         Giacinto Palmieri         42
42            Alex Kolokolov         43
43  Michael E Kirshteyn Ph.D         44
44               Asif Abbasi         45, 'date_dim':         Date  date_id  year  month  day
0 2024-12-22        1  2024     12   22, 'books':     author_id  ...  book_id
0           1  ...        1
1           2  ...        2
2           3  ...        3
3           4  ...        4
4           5  ...        5
5           6  ...        6
6           7  ...        7
7           1  ...        8
8           8  ...        9
9           9  ...       10
10         10  ...       11
11         11  ...       12
12         12  ...       13
13         13  ...       14
14          1  ...       15
15         14  ...       16
16         15  ...       17
17          1  ...       18
18         16  ...       19
19          1  ...       20
20         17  ...       21
21         18  ...       22
22         19  ...       23
23         20  ...       24
24         21  ...       25
25         22  ...       26
26         13  ...       27
27         23  ...       28
28         24  ...       29
29         25  ...       30
30         26  ...       31
31         27  ...       32
32         28  ...       33
33         29  ...       34
34         30  ...       35
35         22  ...       36
36         31  ...       37
37         32  ...       38
38         33  ...       39
39         34  ...       40
40         35  ...       41
41         36  ...       42
42         37  ...       43
43         38  ...       44
44         39  ...       45
45         40  ...       46
46         41  ...       47
47         42  ...       48
48         43  ...       49
49         44  ...       50
50         45  ...       51

[51 rows x 7 columns]}
[2024-12-22T16:05:45.029+0000] {dag_test.py:52} WARNING - <class 'dict'>
[2024-12-22T16:05:45.032+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_test.py", line 54, in load_data_to_postgres
    raise ValueError("Transformed data is missing or not in the expected format")
ValueError: Transformed data is missing or not in the expected format
[2024-12-22T16:05:45.065+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_top_best_sellers_books, task_id=load_data_to_postgres, run_id=manual__2024-12-22T14:55:10.356955+00:00, execution_date=20241222T145510, start_date=20241222T160544, end_date=20241222T160545
[2024-12-22T16:05:45.105+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-22T16:05:45.108+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 37 for task load_data_to_postgres (Transformed data is missing or not in the expected format; 903)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_test.py", line 54, in load_data_to_postgres
    raise ValueError("Transformed data is missing or not in the expected format")
ValueError: Transformed data is missing or not in the expected format
[2024-12-22T16:05:45.194+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-22T16:05:45.505+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-22T16:05:45.512+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
