[2024-12-22T17:38:28.873+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-22T17:38:28.891+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.check_date_exists manual__2024-12-22T17:37:46.953026+00:00 [queued]>
[2024-12-22T17:38:28.901+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.check_date_exists manual__2024-12-22T17:37:46.953026+00:00 [queued]>
[2024-12-22T17:38:28.904+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-22T17:38:28.918+0000] {taskinstance.py:2889} INFO - Executing <Task(ShortCircuitOperator): check_date_exists> on 2024-12-22 17:37:46.953026+00:00
[2024-12-22T17:38:28.927+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1790) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-22T17:38:28.934+0000] {standard_task_runner.py:72} INFO - Started process 1792 to run task
[2024-12-22T17:38:28.931+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_top_best_sellers_books', 'check_date_exists', 'manual__2024-12-22T17:37:46.953026+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpsulx1obq']
[2024-12-22T17:38:28.939+0000] {standard_task_runner.py:105} INFO - Job 59: Subtask check_date_exists
[2024-12-22T17:38:29.329+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_top_best_sellers_books.check_date_exists manual__2024-12-22T17:37:46.953026+00:00 [running]> on host c50092bbd7fa
[2024-12-22T17:38:29.525+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_top_best_sellers_books' AIRFLOW_CTX_TASK_ID='check_date_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T17:37:46.953026+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-22T17:37:46.953026+00:00'
[2024-12-22T17:38:29.529+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-22T17:38:29.546+0000] {baseoperator.py:421} WARNING - ShortCircuitOperator.execute cannot be called outside TaskInstance!
[2024-12-22T17:38:29.560+0000] {base.py:84} INFO - Retrieving connection 'books_connection'
[2024-12-22T17:38:29.569+0000] {sql.py:553} INFO - Running statement: SELECT COUNT(*) FROM date_dim WHERE date = %s;, parameters: ('20241222',)
[2024-12-22T17:38:29.573+0000] {sql.py:562} INFO - Rows affected: 1
[2024-12-22T17:38:29.576+0000] {dag.py:70} INFO - Date 20241222 does not exist in date_dim. Proceeding with data load.
[2024-12-22T17:38:29.581+0000] {python.py:240} INFO - Done. Returned value was: True
[2024-12-22T17:38:29.584+0000] {python.py:309} INFO - Condition result is True
[2024-12-22T17:38:29.586+0000] {python.py:312} INFO - Proceeding with downstream tasks...
[2024-12-22T17:38:29.618+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-22T17:38:29.621+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_top_best_sellers_books, task_id=check_date_exists, run_id=manual__2024-12-22T17:37:46.953026+00:00, execution_date=20241222T173746, start_date=20241222T173828, end_date=20241222T173829
[2024-12-22T17:38:29.658+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-22T17:38:29.889+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-22T17:38:29.893+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
